### PR TITLE
New elo and skill levels

### PR DESCRIPTION
**Pull request by mrubio7**
https://support.faceit.com/hc/en-us/articles/10525200579740-FACEIT-CS2-Elo-and-skill-levels

### CODE REVIEW

**Review by OhGodANoob — APPROVED** [review]
Seems in line with new CS2 ELO Rankings.

[https://support.faceit.com/hc/en-us/articles/10525200579740-FACEIT-CS2-Elo-and-skill-levels](url)

**Review by OhGodANoob — COMMENTED** [review]
Seems in line with new CS2 ELO changes.

[https://support.faceit.com/hc/en-us/articles/10525200579740-FACEIT-CS2-Elo-and-skill-levels](url)

**Comment by noxterr** [comment]
Wouldn't this merge break the CSGO Elo calculation in favor of CS2's?

**Comment by timche** [comment]
Thanks for the PR @mrubio7!

> Wouldn't this merge break the CSGO Elo calculation in favor of CS2's?

Unfortunately this is correct and we need to rewrite this to reflect the correct skill level based on the selected game, but this shouldn't be a lot of work. I'll work on top of this PR to make the required changes.

**Comment by noxterr** [comment]
> Thanks for the PR @mrubio7!
> 
> > Wouldn't this merge break the CSGO Elo calculation in favor of CS2's?
> 
> Unfortunately this is correct and we need to rewrite this to reflect the correct skill level based on the selected game, but this shouldn't be a lot of work. I'll work on top of this PR to make the required changes.

Yeah, my concern is that, if by any chance I switch to CSGO on FACEIT, It'll break the same way it has broken for CS2 until now. But if this is the correct change to be done, we're good

**Comment by OhGodANoob** [comment]
If worried about CSGO and CS2 lobbies conflicting, can maybe designate by URL since the match lobbies are separated.

https://www.faceit.com/en/**cs2**/room/xxx-matchid

https://www.faceit.com/en/**csgo**/room/xxx-matchid

**Comment by timche** [comment]
Match rooms are unaffected by this as Repeek isn't adding any skill level related to it anymore.

**Comment by timche** [comment]
Added support for CS2 skill levels in https://github.com/repeekgg/browser-extension/commit/68f655f9e890eecf5a451f7fade4654e1f73d059

**Pull request closed without merging**
